
export const carMakesAndModelsAndVariants: { [key: string]: { [key: string]: string[] } } = {
    "Maruti Suzuki": {
        "800": ["Std", "AC", "Other"],
        "Alto": ["Std", "LX", "LXi", "VXi", "Other"],
        "Alto K10": ["Std", "LXi", "VXi", "VXi+", "Other"],
        "A-Star": ["LXi", "VXi", "ZXi", "Other"],
        "Baleno": ["Sigma", "Delta", "Zeta", "Alpha", "Other"],
        "Brezza": ["LXi", "VXi", "ZXi", "ZXi+", "Other"],
        "Celerio": ["LXi", "VXi", "ZXi", "Other"],
        "Ciaz": ["Sigma", "Delta", "Zeta", "Alpha", "Other"],
        "Dzire": ["LXi", "VXi", "ZXi", "ZXi+", "Other"],
        "Eeco": ["5 Seater Std", "7 Seater Std", "5 Seater AC", "Cargo", "Other"],
        "Ertiga": ["LXi", "VXi", "ZXi", "ZXi+", "Other"],
        "Esteem": ["LX", "LXi", "VXi", "Other"],
        "Fronx": ["Sigma", "Delta", "Delta+", "Zeta", "Alpha", "Other"],
        "Grand Vitara": ["Sigma", "Delta", "Zeta", "Alpha", "Other"],
        "Gypsy": ["Std", "King", "Other"],
        "Ignis": ["Sigma", "Delta", "Zeta", "Alpha", "Other"],
        "Invicto": ["Zeta+", "Alpha+", "Other"],
        "Jimny": ["Zeta", "Alpha", "Other"],
        "Kizashi": ["CVT", "Other"],
        "Ritz": ["LXi", "VXi", "ZXi", "Other"],
        "S-Cross": ["Sigma", "Delta", "Zeta", "Alpha", "Other"],
        "S-Presso": ["Std", "LXi", "VXi", "VXi+", "Other"],
        "Swift": ["LXi", "VXi", "ZXi", "ZXi+", "Other"],
        "SX4": ["VXi", "ZXi", "Other"],
        "Versa": ["Std", "DX", "Other"],
        "WagonR": ["LXi", "VXi", "ZXi", "Other"],
        "XL6": ["Zeta", "Alpha", "Alpha+", "Other"],
        "Zen": ["LX", "LXi", "VXi", "Other"],
        "Zen Estilo": ["LX", "LXi", "VXi", "Other"],
    },
    "Hyundai": {
        "Accent": ["GLE", "GLS", "Other"],
        "Alcazar": ["Prestige", "Platinum", "Signature", "Other"],
        "Aura": ["E", "S", "SX", "SX+", "Other"],
        "Creta": ["E", "EX", "S", "S+", "SX", "SX(O)", "Other"],
        "Elantra": ["S", "SX", "SX(O)", "Other"],
        "Eon": ["D-Lite", "Era", "Magna", "Sportz", "Other"],
        "Exter": ["EX", "S", "SX", "SX(O)", "Other"],
        "Getz": ["Prime", "GVS", "Other"],
        "Grand i10": ["Era", "Magna", "Sportz", "Asta", "Other"],
        "Grand i10 Nios": ["Era", "Magna", "Sportz", "Asta", "Other"],
        "i10": ["Era", "Magna", "Sportz", "Other"],
        "i20": ["Magna", "Sportz", "Asta", "Asta(O)", "Other"],
        "Ioniq 5": ["GLS", "Other"],
        "Kona Electric": ["Premium", "Other"],
        "Santro": ["Era", "Magna", "Sportz", "Asta", "Other"],
        "Santa Fe": ["2WD", "4WD", "Other"],
        "Sonata": ["Gold", "Other"],
        "Terracan": ["CRDi", "Other"],
        "Tucson": ["Platinum", "Signature", "Other"],
        "Venue": ["E", "S", "S+", "SX", "SX(O)", "Other"],
        "Verna": ["EX", "S", "SX", "SX(O)", "Other"],
        "Xcent": ["Base", "S", "SX", "Other"],
    },
    "Tata": {
        "Altroz": ["XE", "XM", "XT", "XZ", "XZ+", "Other"],
        "Aria": ["Pure", "Pleasure", "Prestige", "Pride", "Other"],
        "Bolt": ["XE", "XM", "XT", "Other"],
        "Curvv": ["Base", "Mid", "Top", "Other"],
        "Harrier": ["XE", "XM", "XT", "XZ", "XZ+", "Other"],
        "Hexa": ["XE", "XM", "XT", "XTA", "XMA", "Other"],
        "Indica": ["DLS", "DLG", "DLX", "Other"],
        "Indigo": ["LS", "LX", "GLS", "GLX", "Other"],
        "Nano": ["Std", "CX", "LX", "Twist", "Other"],
        "Nexon": ["XE", "XM", "XZ", "XZ+", "XZA+", "Other"],
        "Punch": ["Pure", "Adventure", "Accomplished", "Creative", "Other"],
        "Safari": ["XE", "XM", "XT", "XZ", "XZ+", "Other"],
        "Sumo": ["Gold", "Other"],
        "Tiago": ["XE", "XM", "XT", "XZ", "XZ+", "Other"],
        "Tigor": ["XE", "XM", "XZ", "XZ+", "Other"],
        "Zest": ["XE", "XM", "XT", "Other"],
    },
    "Mahindra": {
        "Alturas G4": ["2WD", "4WD", "Other"],
        "Bolero": ["B4", "B6", "B6(O)", "Other"],
        "Bolero Neo": ["N4", "N8", "N10", "N10(O)", "Other"],
        "e2o": ["T0", "T2", "Other"],
        "KUV100": ["K2", "K4", "K6", "K8", "Other"],
        "Marazzo": ["M2", "M4", "M6", "M8", "Other"],
        "NuvoSport": ["N4", "N6", "N8", "Other"],
        "Quanto": ["C2", "C4", "C6", "C8", "Other"],
        "Scorpio": ["S3", "S5", "S7", "S9", "S11", "Other"],
        "Scorpio Classic": ["S", "S11", "Other"],
        "Scorpio-N": ["Z2", "Z4", "Z6", "Z8", "Z8L", "Other"],
        "TUV300": ["T4+", "T6+", "T8", "T10", "T10(O)", "Other"],
        "Thar": ["AX", "LX", "Other"],
        "Verito": ["D2", "D4", "D6", "Other"],
        "Verito Vibe": ["CS", "Other"],
        "XUV300": ["W4", "W6", "W8", "W8(O)", "Other"],
        "XUV 3XO": ["MX1", "MX2", "MX3", "AX5", "AX7", "Other"],
        "XUV400": ["EC", "EL", "Other"],
        "XUV500": ["W3", "W4", "W5", "W6", "W7", "W8", "W8 AWD", "W9", "W10", "W10 AWD", "W11", "W11 AWD", "Other"],
        "XUV700": ["MX", "AX3", "AX5", "AX7", "AX7L", "Other"],
        "Xylo": ["D2", "D4", "H4", "H8", "H9", "Other"],
    },
    "Honda": {
        "Accord": ["L", "L Automatic", "Other"],
        "Amaze": ["S MT", "S CVT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT", "Other"],
        "Brio": ["E MT", "S MT", "S (O) MT", "VX MT", "VX AT", "Other"],
        "BR-V": ["S", "V", "VX", "Other"],
        "City": ["SV MT", "SV CVT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT", "e:HEV", "Other"],
        "Civic": ["V", "VX", "ZX", "Other"],
        "CR-V": ["2WD", "4WD", "Other"],
        "Elevate": ["SV MT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT", "Apex Edition", "Other"],
        "Jazz": ["V MT", "V CVT", "VX MT", "VX CVT", "Other"],
        "Mobilio": ["S", "SV", "V", "Other"],
        "WR-V": ["S", "V", "VX", "Other"],
    },
    "Toyota": {
        "Innova": ["G (2.0 Petrol, 8-Seater)", "GX (2.0 Petrol, 7/8-Seater)", "E (2.5 Diesel, 7/8-Seater)", "G (2.5 Diesel, 7/8-Seater)", "GX (2.5 Diesel, 7/8-Seater)", "VX (2.5 Diesel, 7/8-Seater)", "Z (2.5 Diesel, 7-Seater)", "Other"],
        "Glanza": ["E", "G", "V", "G AMT", "V AMT", "Other"],
        "Urban Cruiser / Taisor": ["G", "V", "S", "Other"],
        "Rumion": ["Base", "Mid", "Top", "Other"],
        "Urban Cruiser Hyryder": ["E", "S", "V", "G", "Other"],
        "Innova Crysta": ["G", "GX", "VX", "ZX", "Other"],
        "Innova Hycross": ["Base Petrol", "Mid Petrol", "Mid Hybrid", "Top Hybrid", "Other"],
        "Fortuner": ["Base Petrol", "Mid Diesel", "Top Diesel AT", "Legender", "Other"],
        "Camry": ["Elegance", "Sprint Edition", "Hybrid", "Other"],
        "Hilux": ["Base", "Mid", "Top", "Other"],
        "Land Cruiser 300": ["Base", "VX", "Sahara", "Other"],
        "Corolla": ["H1", "H2", "H3", "H4", "H5", "Other"],
        "Corolla Altis": ["GL", "GLi", "Sport", "Other"],
        "Etios": ["Liva", "LS", "VD", "Other"],
        "Etios Liva": ["Base", "Mid", "Top", "Other"],
        "Prius": ["Z5", "Z6", "Other"],
        "Qualis": ["GX", "GXL", "Other"],
        "Yaris": ["J", "G", "V", "Other"],
        "Urban Cruiser EV / bZ4X": ["Single Motor", "Dual Motor", "Other"],
    },
    "Ford": {
        "Figo": ["Ambiente", "Titanium", "Titanium Blu", "AT", "Other"],
        "Aspire": ["Ambiente", "Trend", "Titanium", "Titanium+", "AT", "Other"],
        "EcoSport": ["Ambiente", "Trend", "Titanium", "Titanium+", "AT", "Other"],
        "Freestyle": ["Titanium", "Titanium+", "Flair", "Other"],
        "Endeavour": ["Titanium 4x2 AT", "Titanium+ 4x2", "Titanium+ 4x4", "Sport 4x4", "Other"],
        "Fiesta": ["EXi", "S", "SXi", "ZXi", "Other"],
        "Ikon": ["Standard", "Base trims", "Other"],
        "Mondeo": ["Diesel", "Petrol trims", "Other"],
        "Fusion": ["Base", "mid trims", "Other"],
        "Mustang": ["GT V8", "Performance", "Other"],
    },
    "Chevrolet": {
        "Aveo": ["LS", "LT", "LTZ", "Other"],
        "Beat": ["LS", "LT", "LTZ", "Diesel", "Other"],
        "Captiva": ["LT", "LTZ", "4x4", "Other"],
        "Cruze": ["LT", "LTZ", "Diesel", "Petrol", "Other"],
        "Enjoy": ["1.4 LS", "1.4 LT", "1.4 LTZ", "Other"],
        "Optra": ["LS", "LT", "Magnum", "Other"],
        "Sail": ["LS", "LT", "LTZ", "Other"],
        "Sail U-VA": ["LS", "LT", "LTZ", "Other"],
        "Spark": ["LS", "LT", "LTZ", "Other"],
        "Tavera": ["LS", "LT", "Neo", "Other"],
        "Trailblazer": ["LT", "LTZ", "AT", "Other"],
        "Forester": ["Base", "Other"],
    },
    "Volkswagen": {
        "Ameo": ["Trendline", "Comfortline", "Highline", "Highline AT", "Other"],
        "Beetle": ["Classic", "Highline", "Other"],
        "Cross Polo": ["Trendline", "Comfortline", "Highline", "Other"],
        "Polo": ["Trendline", "Comfortline", "Highline", "GT", "Other"],
        "Taigun": ["Trendline", "Comfortline", "Highline", "GT", "Other"],
        "Tiguan": ["Trendline", "Highline", "Allspace", "Other"],
        "T-Roc": ["Trendline", "Style", "Performance", "Other"],
        "Touareg": ["V6", "V8", "Hybrid", "Other"],
        "Jetta": ["Trendline", "Comfortline", "Highline", "Other"],
        "Passat": ["Comfortline", "Highline", "Other"],
        "Phaeton": ["V6", "V8", "Other"],
        "Vento": ["Trendline", "Comfortline", "Highline", "TSI", "Other"],
        "Virtus": ["Trendline", "Comfortline", "Highline", "GT", "Other"],
    },
    "Skoda": {
        "Fabia": ["Active", "Ambition", "Elegance", "Other"],
        "Rapid": ["Active", "Ambition", "Style", "Elegance", "Other"],
        "Slavia": ["Style", "Ambition", "Sport", "Monte Carlo", "Other"],
        "Octavia": ["Ambition", "Style", "L&K", "RS", "Other"],
        "Superb": ["L&K", "Laurin & Klement", "Other"],
        "Kushaq": ["Active", "Ambition", "Style", "Monte Carlo", "Other"],
        "Karoq": ["Ambition", "Style", "L&K", "Other"],
        "Kodiaq": ["Ambition", "Style", "L&K", "Other"],
        "Yeti": ["Elegance", "Ambition", "Other"],
    },
    "Renault": {
        "Kwid": ["Std", "RxE", "RxL", "RxT", "Climber", "Other"],
        "Triber": ["RXE", "RXL", "RXT", "RXZ", "Other"],
        "Duster": ["RxE", "RxL", "RxZ", "AWD", "Other"],
        "Kiger": ["RXE", "RXL", "RXT", "RXZ", "AWD", "Other"],
        "Captur": ["Petrol", "Diesel", "RxZ", "RXZ Premium", "Other"],
        "Lodgy": ["RxE", "RxL", "RxZ", "Other"],
        "Fluence": ["Petrol", "Diesel", "Base", "Mid", "Top", "Other"],
        "Scala": ["RxL", "RxZ", "Other"],
        "Pulse": ["RxE", "RxL", "RxZ", "Other"],
        "Koleos": ["Diesel", "AWD", "Base", "Mid", "Top", "Other"],
    },
    "Nissan": {
        "Micra": ["XL", "XV", "XV Premium", "XV Tech", "Other"],
        "Sunny": ["XE", "XL", "XV", "XV Premium", "Other"],
        "Magnite": ["XE", "XL", "XV", "XV Premium", "XV Premium (O)", "Other"],
        "Kicks": ["XL", "XV", "XV Premium", "XV Premium (O)", "Other"],
        "Terrano": ["XE", "XL", "XV", "XV Premium", "Other"],
        "X-Trail": ["XE", "XL", "XV", "Other"],
        "Teana": ["XE", "XL", "XV", "Other"],
        "GT-R": ["Premium", "Nismo", "Other"],
    },
    "Datsun": {
        "Go": ["D", "A", "T", "T Option", "T Tech", "Other"],
        "Go+": ["D", "A", "T", "T Option", "T Tech", "Other"],
        "redi-GO": ["D", "A", "T", "T Option", "T Tech", "Other"],
    },
    "Kia": {
        "Carens": ["HTE", "HTK", "HTX", "HTX+", "GTX+", "Other"],
        "Carnival": ["Premium", "Limousine", "Limousine Plus", "Other"],
        "EV6": ["Light", "Medium", "GT Line", "Other"],
        "Seltos": ["HTE", "HTK", "HTX", "GTX+", "X-Line", "Other"],
        "Sonet": ["HTE", "HTK", "HTX", "GTX+", "X-Line", "Other"],
    },
    "MG": {
        "Astor": ["Style", "Smart", "Sharp", "Savvy", "Other"],
        "Hector": ["Super", "Smart", "Sharp", "Savvy", "Other"],
        "Hector Plus": ["Smart", "Sharp", "Savvy", "Other"],
        "Gloster": ["Super", "Smart", "Sharp", "Savvy", "Luxury", "Other"],
        "ZS EV": ["Standard", "Excite", "Exclusive", "Other"],
        "Comet EV": ["Base", "Mid", "Top", "Other"],
        "Windsor EV": ["Limited", "Premium", "Other"],
    },
    "Jeep": {
        "Compass": ["Sport", "Longitude", "Limited", "S", "Trailhawk", "Other"],
        "Grand Cherokee": ["Laredo", "Limited", "Summit", "Overland", "Other"],
        "Meridian": ["Limited", "Limited (O)", "Other"],
        "Wrangler": ["Unlimited", "Rubicon", "Other"],
    },
    "Citroen": {
        "C3": ["Live", "Feel", "Shine", "Other"],
        "C3 Aircross": ["Live", "Feel", "Shine", "Other"],
        "C5 Aircross": ["Feel", "Shine", "Shine Pack", "Other"],
        "eC3": ["Base", "Mid", "Top", "Other"],
        "Basalt": ["Limited", "Other"],
    },
    "Fiat": {
        "Punto": ["Active", "Emotion", "Dynamic", "Evo", "Other"],
        "Linea": ["Emotion", "Dynamic", "MJD", "T-Jet", "Other"],
        "Abarth": ["Punto Abarth", "Avventura Abarth", "Other"],
        "Avventura": ["Emotion", "Dynamic", "Emotion MJD", "Other"],
        "Palio": ["ELX", "SX", "Stile", "Other"],
        "Siena": ["EL", "SX", "MJD", "Other"],
        "Uno": ["Standard", "ELX", "Other"],
        "Petra": ["Limited", "Other"],
    },
    "Mitsubishi": {
        "Cedia": ["Select", "Sports", "Other"],
        "Lancer": ["LX", "SFX", "Other"],
        "Montero": ["Base", "Other"],
        "Outlander": ["Base", "Other"],
        "Pajero SFX": ["Base", "Other"],
        "Pajero Sport": ["Base", "Other"],
    },
    "Opel": {
        "Astra": ["L", "LS", "LT", "LTZ", "Other"],
        "Corsa": ["L", "LS", "LT", "LTZ", "Other"],
        "Vectra": ["LS", "GLS", "CD", "Elegance", "Other"],
    },
    "Daewoo": {
        "Cielo": ["Standard", "Other"],
        "Matiz": ["Standard", "Other"],
        "Nexia": ["Standard", "Other"],
    },
    "Others": {
        "Other": ["Other"],
    },
};

export const indianStates = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", 
  "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", 
  "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", 
  "West Bengal", "Andaman and Nicobar Islands", "Chandigarh", 
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", 
  "Ladakh", "Lakshadweep", "Puducherry"
];

export const carColors = [
    "White", "Black", "Silver", "Grey", "Red", "Blue", "Brown", "Beige", "Green", "Yellow", "Orange", "Gold", "Bronze", "Purple", "Other"
];
    
