
export const carMakesAndModelsAndVariants: { [key: string]: { [key: string]: string[] } } = {
    "Maruti Suzuki": {
        "800": ["Std", "AC"],
        "Alto": ["Std", "LX", "LXi", "VXi"],
        "Alto K10": ["Std", "LXi", "VXi", "VXi+"],
        "A-Star": ["LXi", "VXi", "ZXi"],
        "Baleno": ["Sigma", "Delta", "Zeta", "Alpha"],
        "Brezza": ["LXi", "VXi", "ZXi", "ZXi+"],
        "Celerio": ["LXi", "VXi", "ZXi"],
        "Ciaz": ["Sigma", "Delta", "Zeta", "Alpha"],
        "Dzire": ["LXi", "VXi", "ZXi", "ZXi+"],
        "Eeco": ["5 Seater Std", "7 Seater Std", "5 Seater AC", "Cargo"],
        "Ertiga": ["LXi", "VXi", "ZXi", "ZXi+"],
        "Esteem": ["LX", "LXi", "VXi"],
        "Fronx": ["Sigma", "Delta", "Delta+", "Zeta", "Alpha"],
        "Grand Vitara": ["Sigma", "Delta", "Zeta", "Alpha"],
        "Gypsy": ["Std", "King"],
        "Ignis": ["Sigma", "Delta", "Zeta", "Alpha"],
        "Invicto": ["Zeta+", "Alpha+"],
        "Jimny": ["Zeta", "Alpha"],
        "Kizashi": ["CVT"],
        "Ritz": ["LXi", "VXi", "ZXi"],
        "S-Cross": ["Sigma", "Delta", "Zeta", "Alpha"],
        "S-Presso": ["Std", "LXi", "VXi", "VXi+"],
        "Swift": ["LXi", "VXi", "ZXi", "ZXi+"],
        "SX4": ["VXi", "ZXi"],
        "Versa": ["Std", "DX"],
        "WagonR": ["LXi", "VXi", "ZXi"],
        "XL6": ["Zeta", "Alpha", "Alpha+"],
        "Zen": ["LX", "LXi", "VXi"],
        "Zen Estilo": ["LX", "LXi", "VXi"],
    },
    "Hyundai": {
        "Accent": ["GLE", "GLS"],
        "Alcazar": ["Prestige", "Platinum", "Signature"],
        "Aura": ["E", "S", "SX", "SX+"],
        "Creta": ["E", "EX", "S", "S+", "SX", "SX(O)"],
        "Elantra": ["S", "SX", "SX(O)"],
        "Eon": ["D-Lite", "Era", "Magna", "Sportz"],
        "Exter": ["EX", "S", "SX", "SX(O)"],
        "Getz": ["Prime", "GVS"],
        "Grand i10": ["Era", "Magna", "Sportz", "Asta"],
        "Grand i10 Nios": ["Era", "Magna", "Sportz", "Asta"],
        "i10": ["Era", "Magna", "Sportz"],
        "i20": ["Magna", "Sportz", "Asta", "Asta(O)"],
        "Ioniq 5": ["GLS"],
        "Kona Electric": ["Premium"],
        "Santro": ["Era", "Magna", "Sportz", "Asta"],
        "Santa Fe": ["2WD", "4WD"],
        "Sonata": ["Gold"],
        "Terracan": ["CRDi"],
        "Tucson": ["Platinum", "Signature"],
        "Venue": ["E", "S", "S+", "SX", "SX(O)"],
        "Verna": ["EX", "S", "SX", "SX(O)"],
        "Xcent": ["Base", "S", "SX"],
    },
    "Tata": {
        "Altroz": ["XE", "XM", "XT", "XZ", "XZ+"],
        "Aria": ["Pure", "Pleasure", "Prestige", "Pride"],
        "Bolt": ["XE", "XM", "XT"],
        "Curvv": ["Base", "Mid", "Top"],
        "Harrier": ["XE", "XM", "XT", "XZ", "XZ+"],
        "Hexa": ["XE", "XM", "XT", "XTA", "XMA"],
        "Indica": ["DLS", "DLG", "DLX"],
        "Indigo": ["LS", "LX", "GLS", "GLX"],
        "Nano": ["Std", "CX", "LX", "Twist"],
        "Nexon": ["XE", "XM", "XZ", "XZ+", "XZA+"],
        "Punch": ["Pure", "Adventure", "Accomplished", "Creative"],
        "Safari": ["XE", "XM", "XT", "XZ", "XZ+"],
        "Sumo": ["Gold"],
        "Tiago": ["XE", "XM", "XT", "XZ", "XZ+"],
        "Tigor": ["XE", "XM", "XZ", "XZ+"],
        "Zest": ["XE", "XM", "XT"],
    },
    "Mahindra": {
        "Alturas G4": ["2WD", "4WD"],
        "Bolero": ["B4", "B6", "B6(O)"],
        "Bolero Neo": ["N4", "N8", "N10", "N10(O)"],
        "e2o": ["T0", "T2"],
        "KUV100": ["K2", "K4", "K6", "K8"],
        "Marazzo": ["M2", "M4", "M6", "M8"],
        "NuvoSport": ["N4", "N6", "N8"],
        "Quanto": ["C2", "C4", "C6", "C8"],
        "Scorpio": ["S3", "S5", "S7", "S9", "S11"],
        "Scorpio Classic": ["S", "S11"],
        "Scorpio-N": ["Z2", "Z4", "Z6", "Z8", "Z8L"],
        "TUV300": ["T4+", "T6+", "T8", "T10", "T10(O)"],
        "Thar": ["AX", "LX"],
        "Verito": ["D2", "D4", "D6"],
        "Verito Vibe": ["CS"],
        "XUV300": ["W4", "W6", "W8", "W8(O)"],
        "XUV 3XO": ["MX1", "MX2", "MX3", "AX5", "AX7"],
        "XUV400": ["EC", "EL"],
        "XUV500": ["W5", "W7", "W9", "W11"],
        "XUV700": ["MX", "AX3", "AX5", "AX7", "AX7L"],
        "Xylo": ["D2", "D4", "H4", "H8", "H9"],
    },
    "Honda": {
        "Accord": ["L", "L Automatic"],
        "Amaze": ["S MT", "S CVT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT"],
        "Brio": ["E MT", "S MT", "S (O) MT", "VX MT", "VX AT"],
        "BR-V": ["S", "V", "VX"],
        "City": ["SV MT", "SV CVT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT", "e:HEV"],
        "Civic": ["V", "VX", "ZX"],
        "CR-V": ["2WD", "4WD"],
        "Elevate": ["SV MT", "V MT", "V CVT", "VX MT", "VX CVT", "ZX MT", "ZX CVT", "Apex Edition"],
        "Jazz": ["V MT", "V CVT", "VX MT", "VX CVT"],
        "Mobilio": ["S", "SV", "V"],
        "WR-V": ["S", "V", "VX"],
    },
    "Toyota": {
        "Innova": ["G (2.0 Petrol, 8-Seater)", "GX (2.0 Petrol, 7/8-Seater)", "E (2.5 Diesel, 7/8-Seater)", "G (2.5 Diesel, 7/8-Seater)", "GX (2.5 Diesel, 7/8-Seater)", "VX (2.5 Diesel, 7/8-Seater)", "Z (2.5 Diesel, 7-Seater)"],
        "Glanza": ["E", "G", "V", "G AMT", "V AMT"],
        "Urban Cruiser / Taisor": ["G", "V", "S"],
        "Rumion": ["Base", "Mid", "Top"],
        "Urban Cruiser Hyryder": ["E", "S", "V", "G"],
        "Innova Crysta": ["G", "GX", "VX", "ZX"],
        "Innova Hycross": ["Base Petrol", "Mid Petrol", "Mid Hybrid", "Top Hybrid"],
        "Fortuner": ["Base Petrol", "Mid Diesel", "Top Diesel AT", "Legender"],
        "Camry": ["Elegance", "Sprint Edition", "Hybrid"],
        "Hilux": ["Base", "Mid", "Top"],
        "Land Cruiser 300": ["Base", "VX", "Sahara"],
        "Corolla": ["H1", "H2", "H3", "H4", "H5"],
        "Corolla Altis": ["GL", "GLi", "Sport"],
        "Etios": ["Liva", "LS", "VD"],
        "Etios Liva": ["Base", "Mid", "Top"],
        "Prius": ["Z5", "Z6"],
        "Qualis": ["GX", "GXL"],
        "Yaris": ["J", "G", "V"],
        "Urban Cruiser EV / bZ4X": ["Single Motor", "Dual Motor"],
    },
    "Ford": {
        "Figo": ["Ambiente", "Titanium", "Titanium Blu", "AT"],
        "Aspire": ["Ambiente", "Trend", "Titanium", "Titanium+", "AT"],
        "EcoSport": ["Ambiente", "Trend", "Titanium", "Titanium+", "AT"],
        "Freestyle": ["Titanium", "Titanium+", "Flair"],
        "Endeavour": ["Titanium 4x2 AT", "Titanium+ 4x2", "Titanium+ 4x4", "Sport 4x4"],
        "Fiesta": ["EXi", "S", "SXi", "ZXi"],
        "Ikon": ["Standard", "Base trims"],
        "Mondeo": ["Diesel", "Petrol trims"],
        "Fusion": ["Base", "mid trims"],
        "Mustang": ["GT V8", "Performance"],
    },
    "Chevrolet": {
        "Aveo": ["LS", "LT", "LTZ"],
        "Beat": ["LS", "LT", "LTZ", "Diesel"],
        "Captiva": ["LT", "LTZ", "4x4"],
        "Cruze": ["LT", "LTZ", "Diesel", "Petrol"],
        "Enjoy": ["1.4 LS", "1.4 LT", "1.4 LTZ"],
        "Optra": ["LS", "LT", "Magnum"],
        "Sail": ["LS", "LT", "LTZ"],
        "Sail U-VA": ["LS", "LT", "LTZ"],
        "Spark": ["LS", "LT", "LTZ"],
        "Tavera": ["LS", "LT", "Neo"],
        "Trailblazer": ["LT", "LTZ", "AT"],
        "Forester": ["Base"],
    },
    "Volkswagen": {
        "Ameo": ["Trendline", "Comfortline", "Highline", "Highline AT"],
        "Beetle": ["Classic", "Highline"],
        "Cross Polo": ["Trendline", "Comfortline", "Highline"],
        "Polo": ["Trendline", "Comfortline", "Highline", "GT"],
        "Taigun": ["Trendline", "Comfortline", "Highline", "GT"],
        "Tiguan": ["Trendline", "Highline", "Allspace"],
        "T-Roc": ["Trendline", "Style", "Performance"],
        "Touareg": ["V6", "V8", "Hybrid"],
        "Jetta": ["Trendline", "Comfortline", "Highline"],
        "Passat": ["Comfortline", "Highline"],
        "Phaeton": ["V6", "V8"],
        "Vento": ["Trendline", "Comfortline", "Highline", "TSI"],
        "Virtus": ["Trendline", "Comfortline", "Highline", "GT"],
    },
    "Skoda": {
        "Fabia": ["Active", "Ambition", "Elegance"],
        "Rapid": ["Active", "Ambition", "Style", "Elegance"],
        "Slavia": ["Style", "Ambition", "Sport", "Monte Carlo"],
        "Octavia": ["Ambition", "Style", "L&K", "RS"],
        "Superb": ["L&K", "Laurin & Klement"],
        "Kushaq": ["Active", "Ambition", "Style", "Monte Carlo"],
        "Karoq": ["Ambition", "Style", "L&K"],
        "Kodiaq": ["Ambition", "Style", "L&K"],
        "Yeti": ["Elegance", "Ambition"],
    },
    "Renault": {
        "Kwid": ["Std", "RxE", "RxL", "RxT", "Climber"],
        "Triber": ["RXE", "RXL", "RXT", "RXZ"],
        "Duster": ["RxE", "RxL", "RxZ", "AWD"],
        "Kiger": ["RXE", "RXL", "RXT", "RXZ", "AWD"],
        "Captur": ["Petrol", "Diesel", "RxZ", "RXZ Premium"],
        "Lodgy": ["RxE", "RxL", "RxZ"],
        "Fluence": ["Petrol", "Diesel", "Base", "Mid", "Top"],
        "Scala": ["RxL", "RxZ"],
        "Pulse": ["RxE", "RxL", "RxZ"],
        "Koleos": ["Diesel", "AWD", "Base", "Mid", "Top"],
    },
    "Nissan": {
        "Micra": ["XL", "XV", "XV Premium", "XV Tech"],
        "Sunny": ["XE", "XL", "XV", "XV Premium"],
        "Magnite": ["XE", "XL", "XV", "XV Premium", "XV Premium (O)"],
        "Kicks": ["XL", "XV", "XV Premium", "XV Premium (O)"],
        "Terrano": ["XE", "XL", "XV", "XV Premium"],
        "X-Trail": ["XE", "XL", "XV"],
        "Teana": ["XE", "XL", "XV"],
        "GT-R": ["Premium", "Nismo"],
    },
    "Datsun": {
        "Go": ["D", "A", "T", "T Option", "T Tech"],
        "Go+": ["D", "A", "T", "T Option", "T Tech"],
        "redi-GO": ["D", "A", "T", "T Option", "T Tech"],
    },
    "Kia": {
        "Carens": ["HTE", "HTK", "HTX", "HTX+", "GTX+"],
        "Carnival": ["Premium", "Limousine", "Limousine Plus"],
        "EV6": ["Light", "Medium", "GT Line"],
        "Seltos": ["HTE", "HTK", "HTX", "GTX+", "X-Line"],
        "Sonet": ["HTE", "HTK", "HTX", "GTX+", "X-Line"],
    },
    "MG": {
        "Astor": ["Style", "Smart", "Sharp", "Savvy"],
        "Hector": ["Super", "Smart", "Sharp", "Savvy"],
        "Hector Plus": ["Smart", "Sharp", "Savvy"],
        "Gloster": ["Super", "Smart", "Sharp", "Savvy", "Luxury"],
        "ZS EV": ["Standard", "Excite", "Exclusive"],
        "Comet EV": ["Base", "Mid", "Top"],
        "Windsor EV": ["Limited", "Premium"],
    },
    "Jeep": {
        "Compass": ["Sport", "Longitude", "Limited", "S", "Trailhawk"],
        "Grand Cherokee": ["Laredo", "Limited", "Summit", "Overland"],
        "Meridian": ["Limited", "Limited (O)"],
        "Wrangler": ["Unlimited", "Rubicon"],
    },
    "Citroen": {
        "C3": ["Live", "Feel", "Shine"],
        "C3 Aircross": ["Live", "Feel", "Shine"],
        "C5 Aircross": ["Feel", "Shine", "Shine Pack"],
        "eC3": ["Base", "Mid", "Top"],
        "Basalt": ["Limited"],
    },
    "Fiat": {
        "Punto": ["Active", "Emotion", "Dynamic", "Evo"],
        "Linea": ["Emotion", "Dynamic", "MJD", "T-Jet"],
        "Abarth": ["Punto Abarth", "Avventura Abarth"],
        "Avventura": ["Emotion", "Dynamic", "Emotion MJD"],
        "Palio": ["ELX", "SX", "Stile"],
        "Siena": ["EL", "SX", "MJD"],
        "Uno": ["Standard", "ELX"],
        "Petra": ["Limited"],
    },
    "Mitsubishi": {
        "Cedia": ["Select", "Sports"],
        "Lancer": ["LX", "SFX"],
        "Montero": ["Base"],
        "Outlander": ["Base"],
        "Pajero SFX": ["Base"],
        "Pajero Sport": ["Base"],
    },
    "Opel": {
        "Astra": ["L", "LS", "LT", "LTZ"],
        "Corsa": ["L", "LS", "LT", "LTZ"],
        "Vectra": ["LS", "GLS", "CD", "Elegance"],
    },
    "Daewoo": {
        "Cielo": ["Standard"],
        "Matiz": ["Standard"],
        "Nexia": ["Standard"],
    },
    "Others": {
        "Other": ["Other"],
    },
};
